// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SUT23_Labb3_API.Data;

#nullable disable

namespace SUT23_Labb3_API.Migrations
{
    [DbContext(typeof(ILabbDbContext))]
    partial class ILabbDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SUT23_Labb3_API.Models.Interest", b =>
                {
                    b.Property<int>("InterestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterestId"));

                    b.Property<string>("InterestDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterestName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InterestId");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            InterestId = 101,
                            InterestDesc = "Gå runt och slå på en vit boll",
                            InterestName = "Golf"
                        },
                        new
                        {
                            InterestId = 102,
                            InterestDesc = "Springa i en klunga och sparka på en boll",
                            InterestName = "Fotboll"
                        },
                        new
                        {
                            InterestId = 103,
                            InterestDesc = "Sitta och ta det lugnt",
                            InterestName = "Kolla TV"
                        },
                        new
                        {
                            InterestId = 104,
                            InterestDesc = "Sitta och lära sig saker",
                            InterestName = "Studera"
                        });
                });

            modelBuilder.Entity("SUT23_Labb3_API.Models.Link", b =>
                {
                    b.Property<int>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LinkId"));

                    b.Property<int>("PersonInterestId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LinkId");

                    b.HasIndex("PersonInterestId");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            LinkId = 201,
                            PersonInterestId = 1,
                            Url = "www.golf.se"
                        },
                        new
                        {
                            LinkId = 202,
                            PersonInterestId = 1,
                            Url = "www.football.com"
                        },
                        new
                        {
                            LinkId = 203,
                            PersonInterestId = 2,
                            Url = "www.netflix.com"
                        },
                        new
                        {
                            LinkId = 204,
                            PersonInterestId = 2,
                            Url = "www.campus.varberg.se"
                        },
                        new
                        {
                            LinkId = 205,
                            PersonInterestId = 2,
                            Url = "www.aftonbladet.se"
                        });
                });

            modelBuilder.Entity("SUT23_Labb3_API.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            FirstName = "Håkan",
                            LastName = "Svensson",
                            PhoneNumber = "012345678"
                        },
                        new
                        {
                            PersonId = 2,
                            FirstName = "Mats",
                            LastName = "Larsson",
                            PhoneNumber = "45678123"
                        },
                        new
                        {
                            PersonId = 3,
                            FirstName = "Lisa",
                            LastName = "Nilsson",
                            PhoneNumber = "00011678"
                        },
                        new
                        {
                            PersonId = 4,
                            FirstName = "Siv",
                            LastName = "Persson",
                            PhoneNumber = "07868745"
                        });
                });

            modelBuilder.Entity("SUT23_Labb3_API.Models.PersonInterest", b =>
                {
                    b.Property<int>("PersonInterestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonInterestId"));

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("PersonInterestId");

                    b.HasIndex("InterestId");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonInterests");

                    b.HasData(
                        new
                        {
                            PersonInterestId = 1,
                            InterestId = 101,
                            PersonId = 1
                        },
                        new
                        {
                            PersonInterestId = 2,
                            InterestId = 102,
                            PersonId = 2
                        });
                });

            modelBuilder.Entity("SUT23_Labb3_API.Models.Link", b =>
                {
                    b.HasOne("SUT23_Labb3_API.Models.PersonInterest", "PersonInterest")
                        .WithMany("Links")
                        .HasForeignKey("PersonInterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonInterest");
                });

            modelBuilder.Entity("SUT23_Labb3_API.Models.PersonInterest", b =>
                {
                    b.HasOne("SUT23_Labb3_API.Models.Interest", "Interest")
                        .WithMany("PersonInterest")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SUT23_Labb3_API.Models.Person", "Person")
                        .WithMany("PersonInterest")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("SUT23_Labb3_API.Models.Interest", b =>
                {
                    b.Navigation("PersonInterest");
                });

            modelBuilder.Entity("SUT23_Labb3_API.Models.Person", b =>
                {
                    b.Navigation("PersonInterest");
                });

            modelBuilder.Entity("SUT23_Labb3_API.Models.PersonInterest", b =>
                {
                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
